version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    ports:
      - "5000:5000"
      - "1935:1935" 
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://streaming_user:streaming_pass@db:5432/streaming_db?sslmode=disable
      - PORT=5000
    volumes:
      - uploads:/app/uploads
      - backups:/app/backups
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=streaming_db
      - POSTGRES_USER=streaming_user  
      - POSTGRES_PASSWORD=streaming_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  uploads:
  backups: